#!/usr/bin/python


# Version @VERSION@
#
# A plugin for executing script needed by vmops cloud

import XenAPIPlugin
import sys

sys.path.extend(["/opt/xensource/sm/", "/usr/lib/xcp/sm/", "/usr/local/sbin/", "/sbin/"])
import urllib2
import cloudstack_pluginlib as lib
import logging

lib.setup_logging("/var/log/cloud/storageplugin.log")


def echo(fn):
    def wrapped(*v, **k):
        name = fn.__name__
        logging.debug("#### xen plugin enter  %s ####" % name)
        res = fn(*v, **k)
        logging.debug("#### xen plugin exit  %s ####" % name)
        return res

    return wrapped


@echo
def downloadTemplateFromUrl(session, args):
    destPath = args["destPath"]
    srcUrl = args["srcUrl"]
    try:
        template = urllib2.urlopen(srcUrl)
        destFile = open(destPath, "wb")
        destFile.write(template.read())
        destFile.close()
        return "success"
    except:
        logging.debug("exception: " + str(sys.exc_info()))
        return ""


@echo
def getTemplateSize(session, args):
    srcUrl = args["srcUrl"]
    try:
        template = urllib2.urlopen(srcUrl)
        headers = template.info()
        return str(headers["Content-Length"])
    except:
        return ""


if __name__ == "__main__":
    XenAPIPlugin.dispatch({ "downloadTemplateFromUrl": downloadTemplateFromUrl
                              , "getTemplateSize": getTemplateSize
                            })
