#! /usr/bin/python

# Version @VERSION@
#
# A log rotate config for CS plugin log

/ var / log / cloud / cloud.log
{
    daily
size
1
M
rotate
20
}

/ var / log / cloud / ovstunnel.log / var / log / cloud / ovs - pvlan.log / var / log / cloud / swiftxenserver.log / var / log / cloud / s3xenserver.log / var / log / cloud / storageplugin
{
    daily
size
1
M
rotate
2
}
