package com.cloud.utils.db;

import org.junit.Assert;
import org.junit.Test;

public class FilterTest {

    @Test
    /*
    *  This test verifies that the Order By clause generated by the filter is correct and it separates each
    *  order by field with a comma. Using DbTestVO to assert it
    */
    public void testAddOrderBy() {
        final Filter filter = new Filter(DbTestVO.class, "fieldString", true, 1L, 1L);

        Assert.assertTrue(filter.getOrderBy().trim().toLowerCase().equals("order by test.fld_string asc"));

        filter.addOrderBy(DbTestVO.class, "fieldLong", true);

        Assert.assertTrue(filter.getOrderBy().contains(","));
        Assert.assertTrue(filter.getOrderBy().split(",")[1].trim().toLowerCase().equals("test.fld_long asc"));

        filter.addOrderBy(DbTestVO.class, "fieldInt", true);

        Assert.assertTrue(filter.getOrderBy().split(",").length == 3);
        Assert.assertTrue(filter.getOrderBy().split(",")[2].trim().toLowerCase().equals("test.fld_int asc"));
    }
}
