package com.cloud.api;

public enum ApiCommandJobType {
    None,
    VirtualMachine,
    DomainRouter,
    Volume,
    ConsoleProxy,
    Snapshot,
    Template,
    Iso,
    SystemVm,
    Host,
    StoragePool,
    ImageStore,
    IpAddress,
    SecurityGroup,
    PhysicalNetwork,
    TrafficType,
    PhysicalNetworkServiceProvider,
    FirewallRule,
    Account,
    User,
    PrivateGateway,
    StaticRoute,
    LoadBalancerRule,
    AffinityGroup,
    DedicatedGuestVlanRange,
    GuestOs,
    GuestOsMapping,
    Network
}
