package org.apache.cloudstack.engine.entity.api;

import javax.ws.rs.GET;
import java.lang.reflect.Method;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * All entities returned by the Cloud Orchestration Platform must implement
 * this interface.  CloudValueEntity is an immutable representation of
 * an entity exposed by Cloud Orchestration Platform.  For each object, it
 * defines two ids:  uuid, generated by CloudStack Orchestration Platform, and
 * an external id that is set by the caller when the entity is created.  All
 * ids must be unique for that entity.  CloudValueEntity also can be converted
 * to a CloudActionableEntity which contains actions the object can perform.
 */
public interface CloudStackEntity {
    /**
     * @return the uuid of the object.
     */
    @GET
    String getUuid();

    /**
     * @return the id which is often the database id.
     */
    long getId();

    /**
     * @return current state for the entity
     */
    @GET
    String getCurrentState();

    /**
     * @return desired state for the entity
     */
    @GET
    String getDesiredState();

    /**
     * Get the time the entity was created
     */
    @GET
    Date getCreatedTime();

    /**
     * Get the time the entity was last updated
     */
    @GET
    Date getLastUpdatedTime();

    /**
     * @return reference to the owner of this entity
     */
    @GET
    String getOwner();

    /**
     * @return details stored for this entity when created.
     */
    Map<String, String> getDetails();

    void addDetail(String name, String value);

    void delDetail(String name, String value);

    void updateDetail(String name, String value);

    /**
     * @return list of actions that can be performed on the object in its current state
     */
    List<Method> getApplicableActions();
}
